server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Hello2049
    driver-class-name: com.mysql.cj.jdbc.Driver